CREATE TABLE POSTS (
	Post ID INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	url VARCHAR(200) NOT NULL,
	timestamp TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	score INT zerofill NOT NULL DEFAULT NULL,
	USER_NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (Post ID)
);